# Generated by Django 5.1.6 on 2025-03-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('products', '0004_category_keyword_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.product'),
        ),
    ]
