# Generated by Django 5.1.6 on 2025-04-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment_admin_confirmation_comment_article_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
