# Generated by Django 5.1.6 on 2025-04-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
