# Generated by Django 5.1.6 on 2025-04-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_discount_code_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
